# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Elly's Blog
tagline:          'A Jekyll theme'
description:      'Hello!'
url:              https://eunji-elly-lee.github.io/
baseurl:          /

author:
  name:           'Eunji Elly Lee'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Eunji-Elly-Lee/eunji-elly-lee.github.io
